from rest_framework.routers import (
    DefaultRouter,
)  # imports django REST framework's Router
from .views import ContactViewSet  # import the Viewset which was created in views.py

router = DefaultRouter()  # creates a router object
router.register(
    r"contacts", ContactViewSet
)  # whenever someone visits /contacts/ , use ContactViewSet.

urlpatterns = router.urls  # use every URL generated by this route
